# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dsvandet/Software/Private/Bits

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dsvandet/Software/Private/Bits

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dsvandet/Software/Private/Bits/CMakeFiles /Users/dsvandet/Software/Private/Bits//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dsvandet/Software/Private/Bits/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libbits

# Build rule for target.
libbits: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libbits
.PHONY : libbits

# fast build rule for target.
libbits/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/build
.PHONY : libbits/fast

#=============================================================================
# Target rules for targets named bits_benchmark

# Build rule for target.
bits_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bits_benchmark
.PHONY : bits_benchmark

# fast build rule for target.
bits_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/build
.PHONY : bits_benchmark/fast

src/bits/mem/bit_ref.o: src/bits/mem/bit_ref.cc.o
.PHONY : src/bits/mem/bit_ref.o

# target to build an object file
src/bits/mem/bit_ref.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/bit_ref.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/bit_ref.cc.o
.PHONY : src/bits/mem/bit_ref.cc.o

src/bits/mem/bit_ref.i: src/bits/mem/bit_ref.cc.i
.PHONY : src/bits/mem/bit_ref.i

# target to preprocess a source file
src/bits/mem/bit_ref.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/bit_ref.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/bit_ref.cc.i
.PHONY : src/bits/mem/bit_ref.cc.i

src/bits/mem/bit_ref.s: src/bits/mem/bit_ref.cc.s
.PHONY : src/bits/mem/bit_ref.s

# target to generate assembly for a file
src/bits/mem/bit_ref.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/bit_ref.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/bit_ref.cc.s
.PHONY : src/bits/mem/bit_ref.cc.s

src/bits/mem/bit_ref.test.o: src/bits/mem/bit_ref.test.cc.o
.PHONY : src/bits/mem/bit_ref.test.o

# target to build an object file
src/bits/mem/bit_ref.test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/bit_ref.test.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/bit_ref.test.cc.o
.PHONY : src/bits/mem/bit_ref.test.cc.o

src/bits/mem/bit_ref.test.i: src/bits/mem/bit_ref.test.cc.i
.PHONY : src/bits/mem/bit_ref.test.i

# target to preprocess a source file
src/bits/mem/bit_ref.test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/bit_ref.test.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/bit_ref.test.cc.i
.PHONY : src/bits/mem/bit_ref.test.cc.i

src/bits/mem/bit_ref.test.s: src/bits/mem/bit_ref.test.cc.s
.PHONY : src/bits/mem/bit_ref.test.s

# target to generate assembly for a file
src/bits/mem/bit_ref.test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/bit_ref.test.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/bit_ref.test.cc.s
.PHONY : src/bits/mem/bit_ref.test.cc.s

src/bits/mem/fixed_cap_vector.test.o: src/bits/mem/fixed_cap_vector.test.cc.o
.PHONY : src/bits/mem/fixed_cap_vector.test.o

# target to build an object file
src/bits/mem/fixed_cap_vector.test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/fixed_cap_vector.test.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/fixed_cap_vector.test.cc.o
.PHONY : src/bits/mem/fixed_cap_vector.test.cc.o

src/bits/mem/fixed_cap_vector.test.i: src/bits/mem/fixed_cap_vector.test.cc.i
.PHONY : src/bits/mem/fixed_cap_vector.test.i

# target to preprocess a source file
src/bits/mem/fixed_cap_vector.test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/fixed_cap_vector.test.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/fixed_cap_vector.test.cc.i
.PHONY : src/bits/mem/fixed_cap_vector.test.cc.i

src/bits/mem/fixed_cap_vector.test.s: src/bits/mem/fixed_cap_vector.test.cc.s
.PHONY : src/bits/mem/fixed_cap_vector.test.s

# target to generate assembly for a file
src/bits/mem/fixed_cap_vector.test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/fixed_cap_vector.test.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/fixed_cap_vector.test.cc.s
.PHONY : src/bits/mem/fixed_cap_vector.test.cc.s

src/bits/mem/monotonic_buffer.test.o: src/bits/mem/monotonic_buffer.test.cc.o
.PHONY : src/bits/mem/monotonic_buffer.test.o

# target to build an object file
src/bits/mem/monotonic_buffer.test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/monotonic_buffer.test.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/monotonic_buffer.test.cc.o
.PHONY : src/bits/mem/monotonic_buffer.test.cc.o

src/bits/mem/monotonic_buffer.test.i: src/bits/mem/monotonic_buffer.test.cc.i
.PHONY : src/bits/mem/monotonic_buffer.test.i

# target to preprocess a source file
src/bits/mem/monotonic_buffer.test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/monotonic_buffer.test.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/monotonic_buffer.test.cc.i
.PHONY : src/bits/mem/monotonic_buffer.test.cc.i

src/bits/mem/monotonic_buffer.test.s: src/bits/mem/monotonic_buffer.test.cc.s
.PHONY : src/bits/mem/monotonic_buffer.test.s

# target to generate assembly for a file
src/bits/mem/monotonic_buffer.test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/monotonic_buffer.test.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/monotonic_buffer.test.cc.s
.PHONY : src/bits/mem/monotonic_buffer.test.cc.s

src/bits/mem/simd_bit_table.perf.o: src/bits/mem/simd_bit_table.perf.cc.o
.PHONY : src/bits/mem/simd_bit_table.perf.o

# target to build an object file
src/bits/mem/simd_bit_table.perf.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_bit_table.perf.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_bit_table.perf.cc.o
.PHONY : src/bits/mem/simd_bit_table.perf.cc.o

src/bits/mem/simd_bit_table.perf.i: src/bits/mem/simd_bit_table.perf.cc.i
.PHONY : src/bits/mem/simd_bit_table.perf.i

# target to preprocess a source file
src/bits/mem/simd_bit_table.perf.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_bit_table.perf.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_bit_table.perf.cc.i
.PHONY : src/bits/mem/simd_bit_table.perf.cc.i

src/bits/mem/simd_bit_table.perf.s: src/bits/mem/simd_bit_table.perf.cc.s
.PHONY : src/bits/mem/simd_bit_table.perf.s

# target to generate assembly for a file
src/bits/mem/simd_bit_table.perf.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_bit_table.perf.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_bit_table.perf.cc.s
.PHONY : src/bits/mem/simd_bit_table.perf.cc.s

src/bits/mem/simd_bit_table.test.o: src/bits/mem/simd_bit_table.test.cc.o
.PHONY : src/bits/mem/simd_bit_table.test.o

# target to build an object file
src/bits/mem/simd_bit_table.test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_bit_table.test.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_bit_table.test.cc.o
.PHONY : src/bits/mem/simd_bit_table.test.cc.o

src/bits/mem/simd_bit_table.test.i: src/bits/mem/simd_bit_table.test.cc.i
.PHONY : src/bits/mem/simd_bit_table.test.i

# target to preprocess a source file
src/bits/mem/simd_bit_table.test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_bit_table.test.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_bit_table.test.cc.i
.PHONY : src/bits/mem/simd_bit_table.test.cc.i

src/bits/mem/simd_bit_table.test.s: src/bits/mem/simd_bit_table.test.cc.s
.PHONY : src/bits/mem/simd_bit_table.test.s

# target to generate assembly for a file
src/bits/mem/simd_bit_table.test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_bit_table.test.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_bit_table.test.cc.s
.PHONY : src/bits/mem/simd_bit_table.test.cc.s

src/bits/mem/simd_bits.perf.o: src/bits/mem/simd_bits.perf.cc.o
.PHONY : src/bits/mem/simd_bits.perf.o

# target to build an object file
src/bits/mem/simd_bits.perf.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_bits.perf.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_bits.perf.cc.o
.PHONY : src/bits/mem/simd_bits.perf.cc.o

src/bits/mem/simd_bits.perf.i: src/bits/mem/simd_bits.perf.cc.i
.PHONY : src/bits/mem/simd_bits.perf.i

# target to preprocess a source file
src/bits/mem/simd_bits.perf.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_bits.perf.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_bits.perf.cc.i
.PHONY : src/bits/mem/simd_bits.perf.cc.i

src/bits/mem/simd_bits.perf.s: src/bits/mem/simd_bits.perf.cc.s
.PHONY : src/bits/mem/simd_bits.perf.s

# target to generate assembly for a file
src/bits/mem/simd_bits.perf.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_bits.perf.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_bits.perf.cc.s
.PHONY : src/bits/mem/simd_bits.perf.cc.s

src/bits/mem/simd_bits.test.o: src/bits/mem/simd_bits.test.cc.o
.PHONY : src/bits/mem/simd_bits.test.o

# target to build an object file
src/bits/mem/simd_bits.test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_bits.test.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_bits.test.cc.o
.PHONY : src/bits/mem/simd_bits.test.cc.o

src/bits/mem/simd_bits.test.i: src/bits/mem/simd_bits.test.cc.i
.PHONY : src/bits/mem/simd_bits.test.i

# target to preprocess a source file
src/bits/mem/simd_bits.test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_bits.test.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_bits.test.cc.i
.PHONY : src/bits/mem/simd_bits.test.cc.i

src/bits/mem/simd_bits.test.s: src/bits/mem/simd_bits.test.cc.s
.PHONY : src/bits/mem/simd_bits.test.s

# target to generate assembly for a file
src/bits/mem/simd_bits.test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_bits.test.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_bits.test.cc.s
.PHONY : src/bits/mem/simd_bits.test.cc.s

src/bits/mem/simd_bits_range_ref.test.o: src/bits/mem/simd_bits_range_ref.test.cc.o
.PHONY : src/bits/mem/simd_bits_range_ref.test.o

# target to build an object file
src/bits/mem/simd_bits_range_ref.test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_bits_range_ref.test.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_bits_range_ref.test.cc.o
.PHONY : src/bits/mem/simd_bits_range_ref.test.cc.o

src/bits/mem/simd_bits_range_ref.test.i: src/bits/mem/simd_bits_range_ref.test.cc.i
.PHONY : src/bits/mem/simd_bits_range_ref.test.i

# target to preprocess a source file
src/bits/mem/simd_bits_range_ref.test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_bits_range_ref.test.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_bits_range_ref.test.cc.i
.PHONY : src/bits/mem/simd_bits_range_ref.test.cc.i

src/bits/mem/simd_bits_range_ref.test.s: src/bits/mem/simd_bits_range_ref.test.cc.s
.PHONY : src/bits/mem/simd_bits_range_ref.test.s

# target to generate assembly for a file
src/bits/mem/simd_bits_range_ref.test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_bits_range_ref.test.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_bits_range_ref.test.cc.s
.PHONY : src/bits/mem/simd_bits_range_ref.test.cc.s

src/bits/mem/simd_util.o: src/bits/mem/simd_util.cc.o
.PHONY : src/bits/mem/simd_util.o

# target to build an object file
src/bits/mem/simd_util.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_util.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_util.cc.o
.PHONY : src/bits/mem/simd_util.cc.o

src/bits/mem/simd_util.i: src/bits/mem/simd_util.cc.i
.PHONY : src/bits/mem/simd_util.i

# target to preprocess a source file
src/bits/mem/simd_util.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_util.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_util.cc.i
.PHONY : src/bits/mem/simd_util.cc.i

src/bits/mem/simd_util.s: src/bits/mem/simd_util.cc.s
.PHONY : src/bits/mem/simd_util.s

# target to generate assembly for a file
src/bits/mem/simd_util.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_util.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_util.cc.s
.PHONY : src/bits/mem/simd_util.cc.s

src/bits/mem/simd_util.test.o: src/bits/mem/simd_util.test.cc.o
.PHONY : src/bits/mem/simd_util.test.o

# target to build an object file
src/bits/mem/simd_util.test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_util.test.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_util.test.cc.o
.PHONY : src/bits/mem/simd_util.test.cc.o

src/bits/mem/simd_util.test.i: src/bits/mem/simd_util.test.cc.i
.PHONY : src/bits/mem/simd_util.test.i

# target to preprocess a source file
src/bits/mem/simd_util.test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_util.test.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_util.test.cc.i
.PHONY : src/bits/mem/simd_util.test.cc.i

src/bits/mem/simd_util.test.s: src/bits/mem/simd_util.test.cc.s
.PHONY : src/bits/mem/simd_util.test.s

# target to generate assembly for a file
src/bits/mem/simd_util.test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_util.test.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_util.test.cc.s
.PHONY : src/bits/mem/simd_util.test.cc.s

src/bits/mem/simd_word.o: src/bits/mem/simd_word.cc.o
.PHONY : src/bits/mem/simd_word.o

# target to build an object file
src/bits/mem/simd_word.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_word.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_word.cc.o
.PHONY : src/bits/mem/simd_word.cc.o

src/bits/mem/simd_word.i: src/bits/mem/simd_word.cc.i
.PHONY : src/bits/mem/simd_word.i

# target to preprocess a source file
src/bits/mem/simd_word.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_word.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_word.cc.i
.PHONY : src/bits/mem/simd_word.cc.i

src/bits/mem/simd_word.s: src/bits/mem/simd_word.cc.s
.PHONY : src/bits/mem/simd_word.s

# target to generate assembly for a file
src/bits/mem/simd_word.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_word.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_word.cc.s
.PHONY : src/bits/mem/simd_word.cc.s

src/bits/mem/simd_word.perf.o: src/bits/mem/simd_word.perf.cc.o
.PHONY : src/bits/mem/simd_word.perf.o

# target to build an object file
src/bits/mem/simd_word.perf.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_word.perf.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_word.perf.cc.o
.PHONY : src/bits/mem/simd_word.perf.cc.o

src/bits/mem/simd_word.perf.i: src/bits/mem/simd_word.perf.cc.i
.PHONY : src/bits/mem/simd_word.perf.i

# target to preprocess a source file
src/bits/mem/simd_word.perf.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_word.perf.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_word.perf.cc.i
.PHONY : src/bits/mem/simd_word.perf.cc.i

src/bits/mem/simd_word.perf.s: src/bits/mem/simd_word.perf.cc.s
.PHONY : src/bits/mem/simd_word.perf.s

# target to generate assembly for a file
src/bits/mem/simd_word.perf.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_word.perf.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_word.perf.cc.s
.PHONY : src/bits/mem/simd_word.perf.cc.s

src/bits/mem/simd_word.test.o: src/bits/mem/simd_word.test.cc.o
.PHONY : src/bits/mem/simd_word.test.o

# target to build an object file
src/bits/mem/simd_word.test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_word.test.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_word.test.cc.o
.PHONY : src/bits/mem/simd_word.test.cc.o

src/bits/mem/simd_word.test.i: src/bits/mem/simd_word.test.cc.i
.PHONY : src/bits/mem/simd_word.test.i

# target to preprocess a source file
src/bits/mem/simd_word.test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_word.test.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_word.test.cc.i
.PHONY : src/bits/mem/simd_word.test.cc.i

src/bits/mem/simd_word.test.s: src/bits/mem/simd_word.test.cc.s
.PHONY : src/bits/mem/simd_word.test.s

# target to generate assembly for a file
src/bits/mem/simd_word.test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/simd_word.test.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/simd_word.test.cc.s
.PHONY : src/bits/mem/simd_word.test.cc.s

src/bits/mem/sparse_xor_vec.o: src/bits/mem/sparse_xor_vec.cc.o
.PHONY : src/bits/mem/sparse_xor_vec.o

# target to build an object file
src/bits/mem/sparse_xor_vec.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/sparse_xor_vec.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/sparse_xor_vec.cc.o
.PHONY : src/bits/mem/sparse_xor_vec.cc.o

src/bits/mem/sparse_xor_vec.i: src/bits/mem/sparse_xor_vec.cc.i
.PHONY : src/bits/mem/sparse_xor_vec.i

# target to preprocess a source file
src/bits/mem/sparse_xor_vec.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/sparse_xor_vec.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/sparse_xor_vec.cc.i
.PHONY : src/bits/mem/sparse_xor_vec.cc.i

src/bits/mem/sparse_xor_vec.s: src/bits/mem/sparse_xor_vec.cc.s
.PHONY : src/bits/mem/sparse_xor_vec.s

# target to generate assembly for a file
src/bits/mem/sparse_xor_vec.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/sparse_xor_vec.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/sparse_xor_vec.cc.s
.PHONY : src/bits/mem/sparse_xor_vec.cc.s

src/bits/mem/sparse_xor_vec.perf.o: src/bits/mem/sparse_xor_vec.perf.cc.o
.PHONY : src/bits/mem/sparse_xor_vec.perf.o

# target to build an object file
src/bits/mem/sparse_xor_vec.perf.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/sparse_xor_vec.perf.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/sparse_xor_vec.perf.cc.o
.PHONY : src/bits/mem/sparse_xor_vec.perf.cc.o

src/bits/mem/sparse_xor_vec.perf.i: src/bits/mem/sparse_xor_vec.perf.cc.i
.PHONY : src/bits/mem/sparse_xor_vec.perf.i

# target to preprocess a source file
src/bits/mem/sparse_xor_vec.perf.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/sparse_xor_vec.perf.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/sparse_xor_vec.perf.cc.i
.PHONY : src/bits/mem/sparse_xor_vec.perf.cc.i

src/bits/mem/sparse_xor_vec.perf.s: src/bits/mem/sparse_xor_vec.perf.cc.s
.PHONY : src/bits/mem/sparse_xor_vec.perf.s

# target to generate assembly for a file
src/bits/mem/sparse_xor_vec.perf.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/sparse_xor_vec.perf.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/sparse_xor_vec.perf.cc.s
.PHONY : src/bits/mem/sparse_xor_vec.perf.cc.s

src/bits/mem/sparse_xor_vec.test.o: src/bits/mem/sparse_xor_vec.test.cc.o
.PHONY : src/bits/mem/sparse_xor_vec.test.o

# target to build an object file
src/bits/mem/sparse_xor_vec.test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/sparse_xor_vec.test.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/sparse_xor_vec.test.cc.o
.PHONY : src/bits/mem/sparse_xor_vec.test.cc.o

src/bits/mem/sparse_xor_vec.test.i: src/bits/mem/sparse_xor_vec.test.cc.i
.PHONY : src/bits/mem/sparse_xor_vec.test.i

# target to preprocess a source file
src/bits/mem/sparse_xor_vec.test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/sparse_xor_vec.test.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/sparse_xor_vec.test.cc.i
.PHONY : src/bits/mem/sparse_xor_vec.test.cc.i

src/bits/mem/sparse_xor_vec.test.s: src/bits/mem/sparse_xor_vec.test.cc.s
.PHONY : src/bits/mem/sparse_xor_vec.test.s

# target to generate assembly for a file
src/bits/mem/sparse_xor_vec.test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libbits.dir/build.make CMakeFiles/libbits.dir/src/bits/mem/sparse_xor_vec.test.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bits_benchmark.dir/build.make CMakeFiles/bits_benchmark.dir/src/bits/mem/sparse_xor_vec.test.cc.s
.PHONY : src/bits/mem/sparse_xor_vec.test.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bits_benchmark"
	@echo "... libbits"
	@echo "... src/bits/mem/bit_ref.o"
	@echo "... src/bits/mem/bit_ref.i"
	@echo "... src/bits/mem/bit_ref.s"
	@echo "... src/bits/mem/bit_ref.test.o"
	@echo "... src/bits/mem/bit_ref.test.i"
	@echo "... src/bits/mem/bit_ref.test.s"
	@echo "... src/bits/mem/fixed_cap_vector.test.o"
	@echo "... src/bits/mem/fixed_cap_vector.test.i"
	@echo "... src/bits/mem/fixed_cap_vector.test.s"
	@echo "... src/bits/mem/monotonic_buffer.test.o"
	@echo "... src/bits/mem/monotonic_buffer.test.i"
	@echo "... src/bits/mem/monotonic_buffer.test.s"
	@echo "... src/bits/mem/simd_bit_table.perf.o"
	@echo "... src/bits/mem/simd_bit_table.perf.i"
	@echo "... src/bits/mem/simd_bit_table.perf.s"
	@echo "... src/bits/mem/simd_bit_table.test.o"
	@echo "... src/bits/mem/simd_bit_table.test.i"
	@echo "... src/bits/mem/simd_bit_table.test.s"
	@echo "... src/bits/mem/simd_bits.perf.o"
	@echo "... src/bits/mem/simd_bits.perf.i"
	@echo "... src/bits/mem/simd_bits.perf.s"
	@echo "... src/bits/mem/simd_bits.test.o"
	@echo "... src/bits/mem/simd_bits.test.i"
	@echo "... src/bits/mem/simd_bits.test.s"
	@echo "... src/bits/mem/simd_bits_range_ref.test.o"
	@echo "... src/bits/mem/simd_bits_range_ref.test.i"
	@echo "... src/bits/mem/simd_bits_range_ref.test.s"
	@echo "... src/bits/mem/simd_util.o"
	@echo "... src/bits/mem/simd_util.i"
	@echo "... src/bits/mem/simd_util.s"
	@echo "... src/bits/mem/simd_util.test.o"
	@echo "... src/bits/mem/simd_util.test.i"
	@echo "... src/bits/mem/simd_util.test.s"
	@echo "... src/bits/mem/simd_word.o"
	@echo "... src/bits/mem/simd_word.i"
	@echo "... src/bits/mem/simd_word.s"
	@echo "... src/bits/mem/simd_word.perf.o"
	@echo "... src/bits/mem/simd_word.perf.i"
	@echo "... src/bits/mem/simd_word.perf.s"
	@echo "... src/bits/mem/simd_word.test.o"
	@echo "... src/bits/mem/simd_word.test.i"
	@echo "... src/bits/mem/simd_word.test.s"
	@echo "... src/bits/mem/sparse_xor_vec.o"
	@echo "... src/bits/mem/sparse_xor_vec.i"
	@echo "... src/bits/mem/sparse_xor_vec.s"
	@echo "... src/bits/mem/sparse_xor_vec.perf.o"
	@echo "... src/bits/mem/sparse_xor_vec.perf.i"
	@echo "... src/bits/mem/sparse_xor_vec.perf.s"
	@echo "... src/bits/mem/sparse_xor_vec.test.o"
	@echo "... src/bits/mem/sparse_xor_vec.test.i"
	@echo "... src/bits/mem/sparse_xor_vec.test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

